package Baseliner::Model::Inf;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Baseliner::Schema::Inf',
    
    connect_info => {
        dsn => 'dbi:Oracle:host=prusv059;sid=TISO;port=1521',
        user => 'wtscm2',
        password => 'wtscm2',
    }
);

=head1 NAME

Baseliner::Model::Inf - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Baseliner>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Baseliner::Schema::Inf>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
