package Baseliner::Schema::Migrations::0119_modify_structure_favorite_tree;
use Moose;

my $DEFAULT_ICON = '/static/images/icons/favorite.svg';
my $ICON_FOLDER  = '/static/images/icons/favorite-folder-collapsed.svg';
my $FOLDER_URL   = '/lifecycle/tree_favorites?id_folder=%s';

sub upgrade {
    my $self = shift;

    my $all_users = ci->user->find;

    while ( my $user_doc = $all_users->next ) {
        my $user      = ci->new( $user_doc->{mid} );
        my $favorites = $user->favorites;

        my $pos_level_1 = 0;
        foreach my $folder ( keys %$favorites ) {
            $self->_translate_favorite( $favorites, $folder, '', $pos_level_1++ );

            if ( $favorites->{$folder}->{contents} ) {
                my $fav_contents = delete $favorites->{$folder}->{contents};

                my $pos_level_2 = 0;
                foreach my $id_contents ( keys %$fav_contents ) {
                    $self->_translate_favorite( $fav_contents, $id_contents, $folder, $pos_level_2++ );
                    $favorites->{$id_contents} = $fav_contents->{$id_contents};
                }
            }
        }

        $user->save;
    }
}

sub _translate_favorite {
    my $self = shift;
    my ( $favorites, $id, $id_parent, $position ) = @_;

    $favorites->{$id}->{id_parent} = $id_parent;
    delete $favorites->{$id}->{data} if ref( $favorites->{$id}->{data} ) eq 'ARRAY';
    $favorites->{$id}->{data}->{on_drop} = '1';
    delete $favorites->{$id}->{iconCls} if ( $favorites->{$id}->{iconCls} );

    if ( exists $favorites->{$id}->{id_folder} ) {
        $favorites->{$id}->{icon} = $ICON_FOLDER;
    }
    else {

        $favorites->{$id}->{icon}
            = exists $favorites->{$id}->{icon}                  ? $favorites->{$id}->{icon}
            : exists $favorites->{$id}->{data}->{icon}          ? $favorites->{$id}->{data}->{icon}
            : exists $favorites->{$id}->{data}->{click}->{icon} ? $favorites->{$id}->{data}->{click}->{icon}
            :                                                     $DEFAULT_ICON;

        $self->_translate_icon_recursively( $favorites->{$id} );
    }

    $favorites->{$id}->{url} = sprintf( $FOLDER_URL, $id ) if $favorites->{$id}->{id_folder};
    $favorites->{$id}->{position} = $position;
}

sub _translate_icon_recursively {
    my $self = shift;
    my ($hash) = @_;

    foreach my $key_hash ( keys %$hash ) {
        $hash->{$key_hash} = $self->_translate_icon( $hash->{$key_hash} )
            if ( $key_hash eq 'icon' || $key_hash eq 'tab_icon' );
        if ( ref( $hash->{$key_hash} ) eq 'HASH' ) {
            $self->_translate_icon_recursively( $hash->{$key_hash} );
        }
        elsif ( ref( $hash->{$key_hash} ) eq 'ARRAY' ) {
            foreach my $array_hash ( @{ $hash->{$key_hash} } ) {
                $self->_translate_icon_recursively($array_hash) if ref($array_hash) eq 'HASH';
            }
        }
    }
}

sub _translate_icon {
    my $self = shift;
    my ($icon) = @_;

    my $found_icon = '';

    if ($icon) {
        $found_icon = $self->get_icon($icon);

        if ( $found_icon || $icon =~ m/\.svg$/ ) {
            $found_icon = $icon if ( !$found_icon );

            if ( $found_icon =~ m{^/static} ) {
                $found_icon = '' unless -e "root/$found_icon";
            }
            else {
                my ($feature_path) = $found_icon =~ m{^(.*)/};
                $found_icon = '' unless -e "$ENV{CLARIVE_BASE}/features/$feature_path/root/$found_icon";
            }

        }
    }
    $found_icon = $DEFAULT_ICON unless $found_icon;

    return $found_icon;
}

sub get_icon {
    my $self = shift;
    my ($icon) = @_;

    my %old_new_icon = (
        '/static/images/ci/script.png'                   => '/static/images/icons/script.svg',
        '/static/images/ci/dbconn.png'                   => '/static/images/icons/dbconn.svg',
        '/static/images/icons/folder.png'                => '/static/images/icons/favorite-folder-collapsed.svg',
        '/static/images/ci/agent.png'                    => '/static/images/icons/agent.svg',
        '/static/images/ci/folder.png'                   => '/static/images/icons/favorite-folder-collapsed.svg',
        '/static/images/ci/nature.png'                   => '/static/images/icons/nature.svg',
        '/weblogic/weblogic.png'                         => '/weblogic/logo-weblogic.svg',
        '/static/images/icons/role.png'                  => '/static/images/icons/role.svg',
        '/static/images/ci/server.png'                   => '/static/images/icons/server.svg',
        '/static/images/icons/project.png'               => '/static/images/icons/project.svg',
        '/static/images/icons/lc/tree.gif'               => '/static/images/icons/ci-gitrepository-tree.svg',
        '/static/images/ci/class.gif'                    => '/static/images/icons/class.svg',
        '/static/images/icons/git-repo.gif'              => '/static/images/icons/git.svg',
        '/static/images/icons/release.png'               => '/static/images/icons/release.svg',
        '/static/images/icons/topic.png'                 => '/static/images/icons/topic.svg',
        '/static/images/icons/table.png'                 => '/static/images/icons/report.svg',
        '/static/images/icons/release.gif'               => '/static/images/icons/release.svg',
        '/static/images/icons/lc/branch_obj.gif'         => '/static/images/icons/ci-gitrepository-branch.svg',
        '/static/images/icons/report.png'                => '/static/images/icons/report.svg',
        '/static/images/icons/lc/history.gif'            => '/static/images/icons/history.svg',
        '/static/images/icons/lc/status-m.gif'           => '/static/images/icons/ci-gitrepository-changes-status.svg',
        '/static/images/icons/repo.gif'                  => '/static/images/icons/repo.svg',
        '/gitweb/images/icons/commite.png'               => '/static/images/icons/commit.svg',
        '/svn/icons/subversion.png'                      => '/static/images/icons/subversion.svg',
        '/svn/icons/svncommit.png'                       => '/static/images/icons/svncommit.svg',
        '/static/images/icons/folder.gif'                => '/static/images/icons/folder.svg',
        '/static/images/icons/eclipse/commite.png'       => '/static/images/icons/commite.svg',
        '/static/images/icons/release_lc.png'            => '/static/images/icons/release-lc.svg',
        '/static/images/icons/commit.gif'                => '/static/images/icons/commit.svg',
        '/static/images/icons/lc/branches_obj.gif'       => '/static/images/icons/ci-gitrepository-branch.svg',
        '/static/images/icons/project.sv'                => '/static/images/icons/project.svg',
        '/static/images/icons/action.gif'                => '/static/images/icons/action.svg',
        '/static/images/icons/action_folder.gif'         => '/static/images/icons/action-folder.svg',
        '/static/images/icons/action_go.gif'             => '/static/images/icons/action-go.svg',
        '/static/images/icons/action_save.gif'           => '/static/images/icons/save.svg',
        '/static/images/icons/add.gif'                   => '/static/images/icons/add.svg',
        '/static/images/icons/agent.gif'                 => '/static/images/icons/agent.svg',
        '/static/images/icons/application.gif'           => '/static/images/icons/application.svg',
        '/static/images/icons/application_double.gif'    => '/static/images/icons/application-double.svg',
        '/static/images/icons/arrow_down.gif'            => '/static/images/icons/arrow-down.svg',
        '/static/images/icons/arrow_left.gif'            => '/static/images/icons/arrow-left.svg',
        '/static/images/icons/arrow_right.gif'           => '/static/images/icons/arrow-right-color.svg',
        '/static/images/icons/arrow_up.gif'              => '/static/images/icons/arrow-up-color.svg',
        '/static/images/icons/arrow-down.gif'            => '/static/images/icons/arrow-down.svg',
        '/static/images/icons/arrow-up.gif'              => '/static/images/icons/arrow-up-color.svg',
        '/static/images/icons/baseline.gif'              => '/static/images/icons/ci-bl.svg',
        '/static/images/icons/calendar.gif'              => '/static/images/icons/calendar.svg',
        '/static/images/icons/catalog.gif'               => '/static/images/icons/catalog.svg',
        '/static/images/icons/chain.gif'                 => '/static/images/icons/chain.svg',
        '/static/images/icons/checkboxes.gif'            => '/static/images/icons/checkbox.svg',
        '/static/images/icons/class.gif'                 => '/static/images/icons/class.svg',
        '/static/images/icons/clear.gif'                 => '/static/images/icons/clear.svg',
        '/static/images/icons/collapseall.gif'           => '/static/images/icons/collapseall.svg',
        '/static/images/icons/comment_blue.gif'          => '/static/images/icons/topic-comment.svg',
        '/static/images/icons/comment_new.gif'           => '/static/images/icons/comment-new.svg',
        '/static/images/icons/control.gif'               => '/static/images/icons/control.svg',
        '/static/images/icons/control_equalizer.gif'     => '/static/images/icons/control-equalizer.svg',
        '/static/images/icons/copy.gif'                  => '/static/images/icons/copy.svg',
        '/static/images/icons/cut.gif'                   => '/static/images/icons/cut.svg',
        '/static/images/icons/cut_edit.gif'              => '/static/images/icons/cut-edit.svg',
        '/static/images/icons/daemon.gif'                => '/static/images/icons/daemon.svg',
        '/static/images/icons/debug_view.gif'            => '/static/images/icons/debug-view.svg',
        '/static/images/icons/delete.gif'                => '/static/images/icons/delete.svg',
        '/static/images/icons/drive_go.gif'              => '/static/images/icons/drive-go.svg',
        '/static/images/icons/eclipse.gif'               => '/static/images/icons/eclipse.svg',
        '/static/images/icons/edit.gif'                  => '/static/images/icons/edit.svg',
        '/static/images/icons/envelope.gif'              => '/static/images/icons/envelope.svg',
        '/static/images/icons/expandall.gif'             => '/static/images/icons/expandall.svg',
        '/static/images/icons/favorites.gif'             => '/static/images/icons/favorite.svg',
        '/static/images/icons/field-import.gif'          => '/static/images/icons/field-import.svg',
        '/static/images/icons/file.gif'                  => '/static/images/icons/file.svg',
        '/static/images/icons/floppy.gif'                => '/static/images/icons/floppy.svg',
        '/static/images/icons/folder_delete.gif'         => '/static/images/icons/folder-delete.svg',
        '/static/images/icons/folder_new.gif'            => '/static/images/icons/folder-new.svg',
        '/static/images/icons/folder-empty.gif'          => '/static/images/icons/favorite-folder-expanded.svg',
        '/static/images/icons/gears.gif'                 => '/static/images/icons/gears.svg',
        '/static/images/icons/group.gif'                 => '/static/images/icons/group.svg',
        '/static/images/icons/home.gif'                  => '/static/images/icons/home.svg',
        '/static/images/icons/host.gif'                  => '/static/images/icons/host.svg',
        '/static/images/icons/html.gif'                  => '/static/images/icons/logo-html.svg',
        '/static/images/icons/icon_wand.gif'             => '/static/images/icons/icon-wand.svg',
        '/static/images/icons/if.gif'                    => '/static/images/icons/statement-if.svg',
        '/static/images/icons/let.gif'                   => '/static/images/icons/statement-let.svg',
        '/static/images/icons/let.svg'                   => '/static/images/icons/statement-let.svg',
        '/static/images/icons/if_else.gif'               => '/static/images/icons/if_else-green.svg',
        '/static/images/icons/inactive.gif'              => '/static/images/icons/catalog-inactive.svg',
        '/static/images/icons/job.gif'                   => '/static/images/icons/job.svg',
        '/static/ext/resources/images/default/s.gif'     => '/static/images/icons/job.svg',
        '/static/images/icons/leaf.gif'                  => '/static/images/icons/leaf.svg',
        '/static/images/icons/lightbulb.gif'             => '/static/images/icons/lightbulb.svg',
        '/static/images/icons/lightbulb_off.gif'         => '/static/images/icons/lightbulb-off.svg',
        '/static/images/icons/link.gif'                  => '/static/images/icons/link.svg',
        '/static/images/icons/log_d.gif'                 => '/static/images/icons/log-debug.svg',
        '/static/images/icons/log_e.gif'                 => '/static/images/icons/error.svg',
        '/static/images/icons/loop.gif'                  => '/static/images/icons/statement-loop.svg',
        '/static/images/icons/new.gif'                   => '/static/images/icons/catalog-new.svg',
        '/static/images/icons/page.gif'                  => '/static/images/icons/page.svg',
        '/static/images/icons/page_copy.gif'             => '/static/images/icons/page-copy.svg',
        '/static/images/icons/page_refresh.gif'          => '/static/images/icons/page-refresh.svg',
        '/static/images/icons/page_up.gif'               => '/static/images/icons/page-up.svg',
        '/static/images/icons/paperclip.gif'             => '/static/images/icons/paperclip.svg',
        '/static/images/icons/pause.gif'                 => '/static/images/icons/pause.svg',
        '/static/images/icons/post.gif'                  => '/static/images/icons/post.svg',
        '/static/images/icons/public.gif'                => '/static/images/icons/public.svg',
        '/static/images/icons/refresh.gif'               => '/static/images/icons/refresh.svg',
        '/static/images/icons/register_view.gif'         => '/static/images/icons/register-view.svg',
        '/static/images/icons/reload.gif'                => '/static/images/icons/log-jes-reload.svg',
        '/static/images/icons/restart.gif'               => '/static/images/icons/restart.svg',
        '/static/images/icons/retrieve.gif'              => '/static/images/icons/retrieve.svg',
        '/static/images/icons/revision.gif'              => '/static/images/icons/revision.svg',
        '/static/images/icons/revision_create.gif'       => '/static/images/icons/revision-create.svg',
        '/static/images/icons/revision_del.gif'          => '/static/images/icons/revision-del.svg',
        '/static/images/icons/revision_rename.gif'       => '/static/images/icons/revision-rename.svg',
        '/static/images/icons/save.gif'                  => '/static/images/icons/save.svg',
        '/static/images/icons/semaphore.gif'             => '/static/images/icons/semaphore.svg',
        '/static/images/icons/ship.gif'                  => '/static/images/icons/ship.svg',
        '/static/images/icons/sms.gif'                   => '/static/images/icons/sms.svg',
        '/static/images/icons/sql.gif'                   => '/static/images/icons/fieldlet-dbi-query.svg',
        '/static/images/icons/stash.gif'                 => '/static/images/icons/stash.svg',
        '/static/images/icons/state.gif'                 => '/static/images/icons/state.svg',
        '/static/images/icons/tag.gif'                   => '/static/images/icons/tag.svg',
        '/static/images/icons/tag_blocked.gif'           => '/static/images/icons/tag-blocked.svg',
        '/static/images/icons/tag_merged.gif'            => '/static/images/icons/tag-merged.svg',
        '/static/images/icons/tag_pending.gif'           => '/static/images/icons/tag-pending.svg',
        '/static/images/icons/tasks.gif'                 => '/static/images/icons/tasks.svg',
        '/static/images/icons/television.gif'            => '/static/images/icons/television.svg',
        '/static/images/icons/tidy.gif'                  => '/static/images/icons/tidy.svg',
        '/static/images/icons/time.gif'                  => '/static/images/icons/time.svg',
        '/static/images/icons/track.gif'                 => '/static/images/icons/track.svg',
        '/static/images/icons/updown_.gif'               => '/static/images/icons/updown.svg',
        '/static/images/icons/upload.gif'                => '/static/images/icons/upload.svg',
        '/static/images/icons/user.gif'                  => '/static/images/icons/user.svg',
        '/static/images/icons/user_add.gif'              => '/static/images/icons/user-add.svg',
        '/static/images/icons/user_delete.gif'           => '/static/images/icons/user-delete.svg',
        '/static/images/icons/user_female.gif'           => '/static/images/icons/user-female.svg',
        '/static/images/icons/user_suit.gif'             => '/static/images/icons/user-suit.svg',
        '/static/images/icons/users.gif'                 => '/static/images/icons/users.svg',
        '/static/images/icons/values.gif'                => '/static/images/icons/values.svg',
        '/static/images/icons/wrench.gif'                => '/static/images/icons/wrench.svg',
        '/static/images/icons/write.gif'                 => '/static/images/icons/write.svg',
        '/static/images/icons/about.png'                 => '/static/images/icons/about.svg',
        '/static/images/icons/advanced.png'              => '/static/images/icons/advanced.svg',
        '/static/images/icons/agent.png'                 => '/static/images/icons/agent.svg',
        '/static/images/icons/all.png'                   => '/static/images/icons/all.svg',
        '/static/images/icons/application.png'           => '/static/images/icons/application.svg',
        '/static/images/icons/application_add.png'       => '/static/images/icons/application-add.svg',
        '/static/images/icons/application_delete.png'    => '/static/images/icons/application-delete.svg',
        '/static/images/icons/application_double.png'    => '/static/images/icons/application-double.svg',
        '/static/images/icons/application_edit.png'      => '/static/images/icons/application-edit.svg',
        '/static/images/icons/application_go.png'        => '/static/images/icons/application-go.svg',
        '/static/images/icons/area.png'                  => '/static/images/icons/area.svg',
        '/static/images/icons/arrow_down.png'            => '/static/images/icons/arrow-down-color.svg',
        '/static/images/icons/arrow_down_black.png'      => '/static/images/icons/arrow-down.svg',
        '/static/images/icons/arrow_inout.png'           => '/static/images/icons/arrow-inout-color.svg',
        '/static/images/icons/arrow_left.png'            => '/static/images/icons/arrow-left-color.svg',
        '/static/images/icons/arrow_left_black.png'      => '/static/images/icons/arrow-left.svg',
        '/static/images/icons/arrow_redo.png'            => '/static/images/icons/arrow-redo-color.svg',
        '/static/images/icons/arrow_right.png'           => '/static/images/icons/arrow-right-color.svg',
        '/static/images/icons/arrow_right_black.png'     => '/static/images/icons/arrow-right.svg',
        '/static/images/icons/arrow_undo.png'            => '/static/images/icons/arrow-undo-color.svg',
        '/static/images/icons/book.png'                  => '/static/images/icons/jes-spool-job.svg',
        '/static/images/icons/busy.png'                  => '/static/images/icons/busy.svg',
        '/static/images/icons/calendar.png'              => '/static/images/icons/calendar.svg',
        '/static/images/icons/calendar_add.png'          => '/static/images/icons/calendar-add.svg',
        '/static/images/icons/calendar_delete.png'       => '/static/images/icons/calendar-delete.svg',
        '/static/images/icons/calendar_edit.png'         => '/static/images/icons/calendar-edit.svg',
        '/static/images/icons/calendar_link.png'         => '/static/images/icons/calendar-link.svg',
        '/static/images/icons/catalog.png'               => '/static/images/icons/catalog.svg',
        '/static/images/icons/catalog-cart.png'          => '/static/images/icons/catalog-cart.svg',
        '/static/images/icons/catalog-done.png'          => '/static/images/icons/catalog-done.svg',
        '/static/images/icons/catalog-folder.png'        => '/static/images/icons/catalog-folder.svg',
        '/static/images/icons/catalog-form.png'          => '/static/images/icons/catalog-form.svg',
        '/static/images/icons/catalog-light.png'         => '/static/images/icons/catalog-light.svg',
        '/static/images/icons/catalog-target.png'        => '/static/images/icons/catalog-target.svg',
        '/static/images/icons/catalogue.png'             => '/static/images/icons/catalogue.svg',
        '/static/images/icons/catalog-wizard.png'        => '/static/images/icons/catalog-wizard.svg',
        '/static/images/icons/changeset.png'             => '/static/images/icons/changesets.svg',
        '/static/images/icons/changeset_lc.png'          => '/static/images/icons/changesets-lc.svg',
        '/static/images/icons/chart_bar.png'             => '/static/images/icons/chart-bar.svg',
        '/static/images/icons/chart_curve.png'           => '/static/images/icons/chart-curve.svg',
        '/static/images/icons/chart_line.png'            => '/static/images/icons/dashlet-topic-dateline.svg',
        '/static/images/silk/chart_line.png'             => '/static/images/icons/chart-line.svg',
        '/static/images/icons/chart_pie.png'             => '/static/images/icons/chart-pie.svg',
        '/static/images/icons/chart-pie.png'             => '/static/images/icons/chart-pie.svg',
        '/static/images/silk/chart_pie.png'              => '/static/images/icons/chart-pie.svg',
        '/static/images/icons/checkbox.png'              => '/static/images/icons/checkbox.svg',
        '/static/images/icons/checkmark.png'             => '/static/images/icons/checkmark.svg',
        '/static/images/icons/checkout.png'              => '/static/images/icons/feature-checkout.svg',
        '/static/images/icons/ci-generic.png'            => '/static/images/icons/ci-generic.svg',
        '/static/images/icons/circles-four.png'          => '/static/images/icons/circles-four.svg',
        '/static/images/icons/clear.png'                 => '/static/images/icons/clear.svg',
        '/static/images/icons/clear-all.png'             => '/static/images/icons/clear-all.svg',
        '/static/images/icons/clock.png'                 => '/static/images/icons/clock.svg',
        '/static/images/silk/clock.png'                  => '/static/images/icons/clock.svg',
        '/static/images/silk/clock_stop.png'             => '/static/images/icons/job.svg',
        '/static/images/icons/close.png'                 => '/static/images/icons/close.svg',
        '/static/images/icons/cloud.png'                 => '/static/images/icons/cloud.svg',
        '/static/images/icons/cog.png'                   => '/static/images/icons/cog.svg',
        '/static/images/icons/cog_edit.png'              => '/static/images/icons/cog-edit.svg',
        '/static/images/icons/cog_go.png'                => '/static/images/icons/cog-go.svg',
        '/static/images/icons/collapseall.png'           => '/static/images/icons/collapseall.svg',
        '/static/images/icons/combo_box.png'             => '/static/images/icons/combo-box.svg',
        '/static/images/icons/comment_new.png'           => '/static/images/icons/comment-new.svg',
        '/static/images/icons/commit.png'                => '/static/images/icons/commit.svg',
        '/static/images/icons/computer-error.png'        => '/static/images/icons/computer-error.svg',
        '/static/images/icons/connect.png'               => '/static/images/icons/connect.svg',
        '/static/images/icons/console.png'               => '/static/images/icons/console.svg',
        '/static/images/icons/control_equalizer.png'     => '/static/images/icons/control-equalizer.svg',
        '/static/images/icons/control_pause.png'         => '/static/images/icons/control-pause.svg',
        '/static/images/icons/controller.png'            => '/static/images/icons/controller.svg',
        '/static/images/icons/core.png'                  => '/static/images/icons/core.svg',
        '/static/images/icons/d3graph.png'               => '/static/images/icons/d3graph.svg',
        '/static/images/icons/dashboard.png'             => '/static/images/icons/dashboard.svg',
        '/static/images/icons/database_refresh.png'      => '/static/images/icons/database-refresh.svg',
        '/static/images/icons/database_save.png'         => '/static/images/icons/database-save.svg',
        '/static/images/icons/dbconn.png'                => '/static/images/icons/dbconn.svg',
        '/static/images/icons/dbmaster.png'              => '/dbmaestro/logo-dbmaestro.svg',
        '/static/images/icons/debug_view.png'            => '/static/images/icons/debug-view.svg',
        '/static/images/icons/del_all.png'               => '/static/images/icons/delete-grid-all-rows.svg',
        '/static/images/icons/delete.png'                => '/static/images/icons/delete.svg',
        '/static/images/icons/delete_all.png'            => '/static/images/icons/delete-all.svg',
        '/static/images/icons/delete_red.png'            => '/static/images/icons/delete-grid-row.svg',
        '/static/images/icons/destination.png'           => '/static/images/icons/destination.svg',
        '/static/images/icons/detach.png'                => '/static/images/icons/detach.svg',
        '/static/images/icons/detail.png'                => '/static/images/icons/detail.svg',
        '/static/images/icons/diagram.png'               => '/static/images/icons/diagram.svg',
        '/static/images/icons/document.png'              => '/static/images/icons/document.svg',
        '/static/images/icons/door_out.png'              => '/static/images/icons/door-out.svg',
        '/static/images/icons/down.png'                  => '/static/images/icons/down.svg',
        '/static/images/icons/download.png'              => '/static/images/icons/fieldlet-download-all-files.svg',
        '/static/images/icons/downloads_favicon.png'     => '/static/images/icons/downloads-favicon.svg',
        '/static/images/icons/drive.png'                 => '/static/images/icons/drive.svg',
        '/static/images/icons/drive_add.png'             => '/static/images/icons/drive-add.svg',
        '/static/images/icons/drive_delete.png'          => '/static/images/icons/drive-delete.svg',
        '/static/images/icons/drive_disk.png'            => '/static/images/icons/drive-disk.svg',
        '/static/images/icons/drive_edit.png'            => '/static/images/icons/drive-edit.svg',
        '/static/images/icons/drive_go.png'              => '/static/images/icons/drive-go.svg',
        '/static/images/icons/edit.png'                  => '/static/images/icons/edit.svg',
        '/static/images/icons/element_copy.png'          => '/static/images/icons/ci-variable.svg',
        '/static/images/icons/element_new.png'           => '/static/images/icons/element-new.svg',
        '/static/images/icons/element_new_after.png'     => '/static/images/icons/element-new.svg',
        '/static/images/icons/element_new_before.png'    => '/static/images/icons/element-new.svg',
        '/static/images/icons/element_next.png'          => '/static/images/icons/element-next.svg',
        '/static/images/icons/element_previous.png'      => '/static/images/icons/element-previous.svg',
        '/static/images/icons/email.png'                 => '/static/images/icons/email.svg',
        '/static/images/icons/empty.png'                 => '/static/images/icons/ci-empty.svg',
        '/static/images/icons/envelope.png'              => '/static/images/icons/envelope.svg',
        '/static/images/icons/error.png'                 => '/static/images/icons/error.svg',
        '/static/images/icons/error-7-16.png'            => '/static/images/icons/error.svg',
        '/static/images/icons/error-7-64.png'            => '/static/images/icons/error.svg',
        '/static/images/icons/event.png'                 => '/static/images/icons/event.svg',
        '/static/images/icons/expandall.png'             => '/static/images/icons/expandall.svg',
        '/static/images/icons/export.png'                => '/static/images/icons/export.svg',
        '/static/images/icons/exports.png'               => '/static/images/icons/exports.svg',
        '/static/images/icons/extjs.png'                 => '/static/images/icons/extjs.svg',
        '/static/images/icons/extjs_example.png'         => '/static/images/icons/extjs-example.svg',
        '/static/images/icons/extjs_examples.png'        => '/static/images/icons/extjs-examples.svg',
        '/static/images/icons/favorite.png'              => '/static/images/icons/favorite.svg',
        '/static/images/icons/field.png'                 => '/static/images/icons/field.svg',
        '/static/images/icons/field-add.png'             => '/static/images/icons/ci-report-add-field.svg',
        '/static/images/icons/field-add.svg'             => '/static/images/icons/ci-report-add-field.svg',
        '/static/images/icons/file.png'                  => '/static/images/icons/file.svg',
        '/static/images/icons/folder_add.png'            => '/static/images/icons/folder-add.svg',
        '/static/images/icons/folder_database.png'       => '/static/images/icons/folder-database.svg',
        '/static/images/icons/folder_delete.png'         => '/static/images/icons/folder-delete.svg',
        '/static/images/icons/folder_edit.png'           => '/static/images/icons/folder-edit.svg',
        '/static/images/icons/folder_explore.png'        => '/static/images/icons/folder-explore.svg',
        '/static/images/icons/folder_find.png'           => '/static/images/icons/folder-find.svg',
        '/static/images/icons/folder_go.png'             => '/static/images/icons/folder-go.svg',
        '/static/images/icons/folder_heart.png'          => '/static/images/icons/folder-heart.svg',
        '/static/images/icons/folder-close.png'          => '/static/images/icons/folder-close.svg',
        '/static/images/icons/folder-collapsed.png'      => '/static/images/icons/favorite-folder-collapsed.svg',
        '/static/images/icons/folder-expanded.png'       => '/static/images/icons/favorite-folder-expanded.svg',
        '/static/images/icons/form.png'                  => '/static/images/icons/form.svg',
        '/static/images/icons/form_custom.png'           => '/static/images/icons/form-custom.svg',
        '/static/images/icons/fullscreen.png'            => '/static/images/icons/fullscreen.svg',
        '/static/images/icons/fullscreen-24.png'         => '/static/images/icons/fullscreen-arrows.svg',
        '/static/images/icons/gauge.png'                 => '/static/images/icons/dashlet-topic-gauge.svg',
        '/static/images/icons/gears.png'                 => '/static/images/icons/gears.svg',
        '/static/images/icons/git.png'                   => '/static/images/icons/git.svg',
        '/static/images/icons/graphs.png'                => '/static/images/icons/graphs.svg',
        '/static/images/icons/grid.png'                  => '/static/images/icons/grid.svg',
        '/static/images/icons/group.png'                 => '/static/images/icons/group.svg',
        '/static/images/icons/handle.png'                => '/static/images/icons/handle.svg',
        '/static/images/icons/help.png'                  => '/static/images/icons/help.svg',
        '/static/images/icons/html.png'                  => '/static/images/icons/logo-html.svg',
        '/static/images/icons/import.png'                => '/static/images/icons/icon-wand.svg',
        '/static/images/icons/job.png'                   => '/static/images/icons/job.svg',
        '/static/images/icons/js_reload.png'             => '/static/images/icons/js-reload.svg',
        '/static/images/icons/kanban.png'                => '/static/images/icons/kanban.svg',
        '/static/images/icons/key_add.png'               => '/static/images/icons/key-add.svg',
        '/static/images/icons/key_delete.png'            => '/static/images/icons/key-delete.svg',
        '/static/images/icons/keyboard.png'              => '/static/images/icons/keyboard.svg',
        '/static/images/icons/keyboard_add.png'          => '/static/images/icons/keyboard-add.svg',
        '/static/images/icons/layout_edit.png'           => '/static/images/icons/layout_edit.svg',
        '/static/images/icons/leaf.png'                  => '/static/images/icons/leaf.svg',
        '/static/images/icons/left.png'                  => '/static/images/icons/left.svg',
        '/static/images/icons/life_cycle.png'            => '/static/images/icons/life-cycle.svg',
        '/static/images/icons/life_cycle_general.png'    => '/static/images/icons/life-cycle-general.svg',
        '/static/images/icons/life_cycle_rol.png'        => '/static/images/icons/life-cycle-rol.svg',
        '/static/images/icons/lightbulb.png'             => '/static/images/icons/lightbulb.svg',
        '/static/images/icons/lightbulb_off.png'         => '/static/images/icons/lightbulb-off.svg',
        '/static/images/icons/listbox.png'               => '/static/images/icons/fieldlet-system-topics.svg',
        '/static/images/icons/local.png'                 => '/static/images/icons/local.svg',
        '/static/images/icons/script-local.png'          => '/static/images/icons/script.svg',
        '/static/images/icons/lock_small.png'            => '/static/images/icons/lock.svg',
        '/static/images/icons/log.png'                   => '/static/images/icons/log.svg',
        '/static/images/icons/log_e.png'                 => '/static/images/icons/error.svg',
        '/static/images/icons/log_i.png'                 => '/static/images/icons/active.svg',
        '/static/images/icons/log_w.png'                 => '/static/images/icons/job-log-warn.svg',
        '/static/images/icons/logout.png'                => '/static/images/icons/logout.svg',
        '/static/images/icons/magnifier.png'             => '/static/images/icons/magnifier.svg',
        '/static/images/icons/mainframe.png'             => '/static/images/icons/mainframe.svg',
        '/static/images/icons/manual.png'                => '/static/images/icons/manual.svg',
        '/static/images/icons/mark_unread.png'           => '/static/images/icons/mark-unread.svg',
        '/static/images/icons/milestone.png'             => '/static/images/icons/milestone.svg',
        '/static/images/icons/mind_map-26.png'           => '/static/images/icons/mind-map.svg',
        '/static/images/icons/nature.png'                => '/static/images/icons/nature.svg',
        '/static/images/icons/nature.gif'                => '/static/images/icons/nature.svg',
        '/static/images/icons/number.png'                => '/static/images/icons/number.svg',
        '/static/images/icons/open.png'                  => '/static/images/icons/open.svg',
        '/static/images/icons/package_add.png'           => '/static/images/icons/package-add.svg',
        '/static/images/icons/package2.png'              => '/static/images/icons/package-open.svg',
        '/static/images/icons/page.png'                  => '/static/images/icons/page.svg',
        '/static/images/icons/password.png'              => '/static/images/icons/password.svg',
        '/static/images/icons/paste.png'                 => '/static/images/icons/paste.svg',
        '/static/images/icons/paused.png'                => '/static/images/icons/pause.svg',
        '/static/images/icons/pencil.png'                => '/static/images/icons/pencil.svg',
        '/static/images/icons/perl.png'                  => '/static/images/icons/perl.svg',
        '/static/images/icons/pills.png'                 => '/static/images/icons/fieldlet-pills.svg',
        '/static/images/icons/play.png'                  => '/static/images/icons/play.svg',
        '/static/images/icons/post.png'                  => '/static/images/icons/post.svg',
        '/static/images/icons/prefs.png'                 => '/static/images/icons/prefs.svg',
        '/static/images/icons/printer.png'               => '/static/images/icons/printer.svg',
        '/static/images/icons/priority_request.png'      => '/static/images/icons/priority-request.svg',
        '/static/images/icons/progressbar.png'           => '/static/images/icons/fieldlet-progressbar.svg',
        '/static/images/icons/properties.png'            => '/static/images/icons/properties.svg',
        '/static/images/icons/redo.png'                  => '/static/images/icons/redo.svg',
        '/static/images/icons/redraw.png'                => '/static/images/icons/redraw.svg',
        '/static/images/icons/referenced_in.png'         => '/static/images/icons/referenced-in.svg',
        '/static/images/icons/references_out.png'        => '/static/images/icons/references-out.svg',
        '/static/images/icons/refresh.png'               => '/static/images/icons/refresh.svg',
        '/static/images/icons/release_explorer.png'      => '/static/images/icons/release-explorer.svg',
        '/static/images/icons/release-dark.png'          => '/static/images/icons/release-dark.svg',
        '/static/images/icons/report_default.png'        => '/static/images/icons/report-default.svg',
        '/static/images/icons/report_magnify.png'        => '/static/images/icons/report-magnify.svg',
        '/static/images/icons/reports.png'               => '/static/images/icons/reports.svg',
        '/static/images/icons/restart.png'               => '/static/images/icons/restart.svg',
        '/static/images/icons/restart_new.png'           => '/static/images/icons/restart-new.svg',
        '/static/images/icons/restart-left.png'          => '/static/images/icons/restart-left.svg',
        '/static/images/icons/rgraph.png'                => '/static/images/icons/rgraph.svg',
        '/static/images/icons/rule.png'                  => '/static/images/icons/rule.svg',
        '/static/images/icons/save.png'                  => '/static/images/icons/save.svg',
        '/static/images/icons/scaleTime.png'             => '/static/images/icons/scale-time.svg',
        '/static/images/icons/script.png'                => '/static/images/icons/script.svg',
        '/static/images/icons/script_edit.png'           => '/static/images/icons/script-edit.svg',
        '/static/images/icons/search-small.png'          => '/static/images/icons/search-small.svg',
        '/static/images/icons/search-small-white.png'    => '/static/images/icons/search-small-white.svg',
        '/static/images/icons/search-values.png'         => '/static/images/icons/search-values.svg',
        '/static/images/icons/separator.png'             => '/static/images/icons/separator.svg',
        '/static/images/icons/sequence.png'              => '/static/images/icons/sequence.svg',
        '/static/images/icons/server.png'                => '/static/images/icons/server.svg',
        '/static/images/icons/server_restart.png'        => '/static/images/icons/server-restart.svg',
        '/static/images/icons/server-error.png'          => '/static/images/icons/server-error.svg',
        '/static/images/icons/service.png'               => '/static/images/icons/service.svg',
        '/static/images/icons/shortcut.png'              => '/static/images/icons/shortcut.svg',
        '/static/images/icons/shortcut-add.png'          => '/static/images/icons/shortcut-add.svg',
        '/static/images/icons/slot.png'                  => '/static/images/icons/slot.svg',
        '/static/images/icons/slot_green.png'            => '/static/images/icons/create-slot-active.svg',
        '/static/images/icons/slot_red.png'              => '/static/images/icons/create-slot-inactive.svg',
        '/static/images/icons/small_loading_static.png'  => '/static/images/icons/loading-static.svg',
        '/static/images/icons/sms.png'                   => '/static/images/icons/sms.svg',
        '/static/images/icons/spacetree.png'             => '/static/images/icons/graph-tree.svg',
        '/static/images/icons/spool.png'                 => '/static/images/icons/spool.svg',
        '/static/images/icons/sql.png'                   => '/static/images/icons/fieldlet-dbi-query.svg',
        '/static/images/icons/startlast.png'             => '/static/images/icons/startlast.svg',
        '/static/images/icons/stash.png'                 => '/static/images/icons/stash.svg',
        '/static/images/icons/status.png'                => '/static/images/icons/state.svg',
        '/static/images/icons/step_post.png'             => '/static/images/icons/step-post.svg',
        '/static/images/icons/step_pre.png'              => '/static/images/icons/step-pre.svg',
        '/static/images/icons/step_run.png'              => '/static/images/icons/script.svg',
        '/static/images/icons/stop.png'                  => '/static/images/icons/stop.svg',
        '/static/images/icons/surrogate.png'             => '/static/images/icons/surrogate.svg',
        '/static/images/icons/swarm.png'                 => '/static/images/icons/dashlet-swarm.svg',
        '/static/images/icons/tab.png'                   => '/static/images/icons/tab.svg',
        '/static/images/icons/table_edit.png'            => '/static/images/icons/table-edit.svg',
        '/static/images/icons/television.png'            => '/static/images/icons/television.svg',
        '/static/images/icons/textfield.png'             => '/static/images/icons/fieldlet-system-description.svg',
        '/static/images/icons/time.png'                  => '/static/images/icons/time.svg',
        '/static/images/icons/timeline.png'              => '/static/images/icons/timeline.svg',
        '/static/images/icons/topic_in.png'              => '/static/images/icons/topic-in.svg',
        '/static/images/icons/topic_lc.png'              => '/static/images/icons/topic-lc.svg',
        '/static/images/icons/topic_out.png'             => '/static/images/icons/topic-out.svg',
        '/static/images/icons/topic_one.png'             => '/static/images/icons/topic.svg',
        '/static/images/icons/topic-grid.png'            => '/static/images/icons/topic-grid.svg',
        '/static/images/icons/topic-out-open.png'        => '/static/images/icons/topic-out-open.svg',
        '/static/images/icons/traffic_lights.png'        => '/static/images/icons/traffic-lights.svg',
        '/static/images/icons/traffic_lights_green.png'  => '/static/images/icons/traffic-lights-green.svg',
        '/static/images/icons/traffic_lights_red.png'    => '/static/images/icons/traffic-lights-red.svg',
        '/static/images/icons/traffic_lights_yellow.png' => '/static/images/icons/traffic-lights-yellow.svg',
        '/static/images/icons/undo.png'                  => '/static/images/icons/undo.svg',
        '/static/images/icons/up.png'                    => '/static/images/icons/up.svg',
        '/static/images/icons/update.png'                => '/static/images/icons/update.svg',
        '/static/images/icons/upgrade.png'               => '/static/images/icons/upgrade.svg',
        '/static/images/icons/user.png'                  => '/static/images/icons/user.svg',
        '/static/images/icons/user_suit.png'             => '/static/images/icons/user-suit.svg',
        '/static/images/icons/users.png'                 => '/static/images/icons/users.svg',
        '/static/images/icons/views.png'                 => '/static/images/icons/views.svg',
        '/static/images/icons/waiting.png'               => '/static/images/icons/waiting.svg',
        '/static/images/icons/weblogic.png'              => '/static/images/icons/weblogic.svg',
        '/static/images/icons/webservice.png'            => '/static/images/icons/ci-web-instance.svg',
        '/static/images/icons/where.png'                 => '/static/images/icons/where.svg',
        '/static/images/icons/window_min.png'            => '/static/images/icons/window-min.svg',
        '/static/images/icons/wipe_cache.png'            => '/static/images/icons/wipe-cache.svg',
        '/static/images/icons/workflow.png'              => '/static/images/icons/workflow.svg',
        '/static/images/icons/workspace.png'             => '/static/images/icons/workspace.svg',
        '/static/images/icons/world.png'                 => '/static/images/icons/world.svg',
        '/static/images/icons/wrench.png'                => '/static/images/icons/wrench.svg',
        '/static/images/icons/commite_new_.png'          => '/static/images/icons/commite-new.svg',
        '/static/images/icons/coverage.png'              => '/coverage/coverage.svg',
        '/static/images/icons/dbmaster_color.png'        => '/dbmaestro/logo-dbmaestro.svg',
        '/docker/docker.png'                             => '/docker/logo-docker.svg',
        '/static/images/host.gif'                        => '/endevor/host.svg',
        '/static/images/icons/package_red.gif'           => '/endevor/package-red.svg',
        '/static/images/scm/debug/debug_view.gif'        => '/endevor/debug-view.svg',
        '/static/images/scm/debug/genericregister_obj.gif' => '/endevor/genericregister-obj.svg',
        '/static/images/scm/debug/hierarchicalLayout.gif'  => '/endevor/hierarchicalLayout.svg',
        '/static/images/scm/debug/memory_view.gif'         => '/endevor/memory-view.svg',
        '/static/images/scm/debug/write_obj.gif'           => '/endevor/write-obj.svg',
        '/static/images/icons/arrow_refresh.gif'           => '/endevor/arrow-refresh.svg',
        '/static/images/scm/debug/delete_config.gif'       => '/endevor/delete-config.svg',
        '/static/images/icons/endevor.png'                 => '/endevor/logo-endevor.svg',
        '/force.com/images/icons/force.com.ico'            => '/force.com/logo-forcecom.svg',
        '/icons/jboss_icon.png'                            => '/jboss/jboss.svg',
        '/jira/jira.ico'                                   => '/jira/logo-jira.svg',
        '/static/images/icons/job-full-log.png'            => '/static/images/icons/moredata.svg',
        '/static/images/icons/calendar_view_month.png'     => '/static/images/icons/calendar.svg',
        '/nexus/nexus.png'                                 => '/nexus/logo-nexus.svg',
        '/static/images/silk/brick.png'                    => '/nexus/brick.svg',
        '/static/images/scm/version.gif'                   => '/nexus/version.svg',
        '/static/icons/plastic_icon.png'                   => '/plasticscm/plastic-icon.svg',
        '/static/icons/plastic_revision.png'               => '/plasticscm/plastic-revision.svg',
        '/static/images/silk/arrow_up.gif'                 => '/plasticscm/arrow-up.svg',
        '/static/images/icons/tag_%s.gif'                  => '/plasticscm/tag-%s.svg',
        '/gitweb/images/icons/git.png'                     => '/static/images/icons/git.svg',
        '/static/images/silk/arrow_right.gif'              => '/plasticscm/arrow-right.svg',
        '/static/images/silk/arrow_down.gif'               => '/plasticscm/arrow-down.svg',
        '/gitweb/images/icons/commit.gif'                  => '/plasticscm/commit.svg',
        '/openvz/openvz_16.png'                            => '/openvz/logo-openvz.svg',
        '/images/quality.png'                              => '/sqa/logo-sqa.svg',
        '/images/help.png'                                 => '/sqa/help.svg',
        '/static/images/silk/arrow_up.png'                 => '/sqa/arrow-up.svg',
        '/static/images/silk/arrow_refresh.png'            => '/sqa/arrow-refresh.svg',
        '/static/images/silk/arrow_down.png'               => '/sqa/arrow-down.svg',
        '/static/images/silk/table_delete.png'             => '/sqa/table-delete.svg',
        '/static/images/silk/rosette.png'                  => '/sqa/rosette.svg',
        '/static/images/silk/folder_magnify.png'           => '/sqa/folder-magnify.svg',
        '/static/images/nature/nature.png'                 => '/static/images/nature/nature.svg',
        '/static/images/icons/flag_green.png'              => '/sqa/flag-green.svg',
        '/static/images/icons/flag_red.png'                => '/sqa/flag-red.svg',
        '/static/images/silk/action_refresh.gif'           => '/sqa/action-refresh.svg',
        '/servicenow/servicenow.ico'                       => '/servicenow/logo-servicenow.svg',
        '/static/images/silk/lightning.png'                => '/support/table-lightning.svg',
        '/static/images/silk/icon_user.gif'                => '/support/user.svg',
        '/static/images/icons/lc/changes.gif'              => '/svnscm/changes.svg',
        '/ucm/ucm.png'                                     => '/ucm/ucm.svg',
        '/static/images/icons/mime/file_extension_bin.png' => '/ucm/file-extension-bin.svg',
        '/images/wpmini.png'                               => '/wordpress/logo-wordpress.svg',
        '/kiuwan/kiuwan.png'                               => '/kiuwan/logo-kiuwan.svg',
        '/static/images/icons/favorite-folder.svg'         => '/static/images/icons/favorite.svg',
        '/static/images/icons/favorite_new.svg'            => '/static/images/icons/favorite.svg',
        '/maven/maven.png'                                 => '/maven/maven.svg',
        '/static/images/icons/application-server.svg'      => '/static/images/icons/app-server.svg',
        '/static/images/icons/arrow-down.svg'              => '/static/images/icons/arrow-down-color.svg',
        '/static/images/icons/arrow_down_short.svg'        => '/static/images/icons/arrow-down-short-color.svg',
        '/static/images/icons/arrow-down-inout.svg'        => '/static/images/icons/arrow-inout-color.svg',
        '/static/images/icons/arrow_left.svg'              => '/static/images/icons/arrow-left-color.svg',
        '/static/images/icons/arrow-redo.svg'              => '/static/images/icons/arrow-redo-color.svg',
        '/static/images/icons/arrow_right.svg'             => '/static/images/icons/arrow-right-color.svg',
        '/static/images/icons/arrow_undo.svg'              => '/static/images/icons/arrow-undo-color.svg',
        '/static/images/icons/arrow-up.svg'                => '/static/images/icons/arrow-up-color.svg',
        '/static/images/icons/arrow_up_short.svg'          => '/static/images/icons/arrow-up-short-color.svg',
        '/static/images/icons/baseline.svg'                => '/static/images/icons/ci-bl.svg',
        '/static/images/icons/branch.svg'                  => '/static/images/icons/ci-gitrepository-branch.svg',
        '/static/images/icons/btn-arrow-gray.svg'          => '/static/images/icons/btn-arrow.svg',
        '/static/images/icons/catalog.svg'                 => '/static/images/icons/catalog.svg',
        '/static/images/icons/changes.svg'                 => '/static/images/icons/ci-gitrepository-changes.svg',
        '/static/images/icons/checkout.svg'                => '/static/images/icons/feature-checkout.svg',
        '/static/images/icons/checkout-database.svg'       => '/static/images/icons/checkout-database.svg',
        '/static/images/icons/collapseall.svg'             => '/static/images/icons/collapseall.svg',
        '/static/images/icons/database-table.svg'          => '/static/images/icons/feature-database-table.svg',
        '/static/images/icons/del_all.svg'                 => '/static/images/icons/delete-grid-all-rows.svg',
        '/static/images/icons/element_copy.svg'            => '/static/images/icons/ci-variable.svg',
        '/static/images/icons/empty.svg'                   => '/static/images/icons/ci-empty.svg',
        '/static/images/icons/error.svg'                   => '/static/images/icons/error-triangule-orange.svg',
        '/static/images/icons/expand.svg'                  => '/static/images/icons/expand.svg',
        '/static/images/icons/expandall.svg'               => '/static/images/icons/expandall.svg',
        '/static/images/icons/favorite.svg'                => '/static/images/icons/favorite.svg',
        '/static/images/icons/folder-collapsed.svg'        => '/static/images/icons/favorite-folder-collapsed.svg',
        '/static/images/icons/folder-expanded.svg'         => '/static/images/icons/favorite-folder-expanded.svg',
        '/static/images/icons/forbidden.svg'               => '/static/images/icons/forbidden.svg',
        '/static/images/icons/fullscreen_24.svg'           => '/static/images/icons/fullscreen-arrows.svg',
        '/static/images/icons/html.svg'                    => '/static/images/icons/logo-html.svg',
        '/static/images/icons/if.svg'                      => '/static/images/icons/statement-if.svg',
        '/static/images/icons/inactive.svg'                => '/static/images/icons/catalog-inactive.svg',
        '/static/images/icons/lock_small.svg'              => '/static/images/icons/lock.svg',
        '/static/images/icons/log_w_1.svg'                 => '/static/images/icons/job-log-warn.svg',
        '/static/images/icons/loop.svg'                    => '/static/images/icons/statement-loop.svg',
        '/static/images/icons/new.svg'                     => '/static/images/icons/catalog-new.svg',
        '/static/images/icons/reload.svg'                  => '/static/images/icons/log-jes-reload.svg',
        '/static/images/icons/restart.svg'                 => '/static/images/icons/job-restart.svg',
        '/static/images/icons/row-check-sprite-1.svg'      => '/static/images/icons/row-check-sprite-triple.svg',
        '/static/images/icons/scaleTime.svg'               => '/static/images/icons/scale-time.svg',
        '/static/images/icons/small_loading_static.svg'    => '/static/images/icons/loading-static.svg',
        '/static/images/icons/spacetree.svg'               => '/static/images/icons/graph-tree.svg',
        '/static/images/icons/startlast.svg'               => '/static/images/icons/startlast.svg',
        '/static/images/icons/status-m.svg'             => '/static/images/icons/ci-gitrepository-changes-status.svg',
        '/static/images/icons/stop.svg'                 => '/static/images/icons/stop.svg',
        '/static/images/icons/tree.svg'                 => '/static/images/icons/ci-gitrepository-tree.svg',
        '/static/images/icons/unknown.svg'              => '/static/images/icons/event-status-unknown.svg',
        '/static/images/icons/webservice.svg'           => '/static/images/icons/ci-web-instance.svg',
        '/static/images/icons/action_folder.svg'        => '/static/images/icons/action-folder.svg',
        '/static/images/icons/action_go.svg'            => '/static/images/icons/action-go.svg',
        '/static/images/icons/add_new_form_16.svg'      => '/static/images/icons/add-new-form.svg',
        '/static/images/icons/add_new_form.svg'         => '/static/images/icons/add-new-form.svg',
        '/static/images/icons/admin_request.svg'        => '/static/images/icons/fieldlet-checkbox.svg',
        '/static/images/icons/application_add.svg'      => '/static/images/icons/application-add.svg',
        '/static/images/icons/application_delete.svg'   => '/static/images/icons/application-delete.svg',
        '/static/images/icons/application_double.svg'   => '/static/images/icons/application-double.svg',
        '/static/images/icons/application_edit.svg'     => '/static/images/icons/application-edit.svg',
        '/static/images/icons/application_go.svg'       => '/static/images/icons/application-go.svg',
        '/static/images/icons/arrow_down_black.svg'     => '/static/images/icons/arrow-down.svg',
        '/static/images/icons/arrow_inout.svg'          => '/static/images/icons/arrow-inout.svg',
        '/static/images/icons/arrow_left_black.svg'     => '/static/images/icons/arrow-left.svg',
        '/static/images/icons/arrow_right_black.svg'    => '/static/images/icons/arrow-right.svg',
        '/static/images/icons/branch_obj.svg'           => '/static/images/icons/ci-gitrepository-branch.svg',
        '/static/images/icons/calendar_add.svg'         => '/static/images/icons/calendar-add.svg',
        '/static/images/icons/calendar_by_day.svg'      => '/static/images/icons/calendar-by-day.svg',
        '/static/images/icons/calendar_by_week.svg'     => '/static/images/icons/calendar-by-week.svg',
        '/static/images/icons/calendar_delete.svg'      => '/static/images/icons/calendar-delete.svg',
        '/static/images/icons/calendar_edit.svg'        => '/static/images/icons/calendar-edit.svg',
        '/static/images/icons/calendar_link.svg'        => '/static/images/icons/calendar-link.svg',
        '/static/images/icons/catalog_1.svg'            => '/static/images/icons/catalogue.svg',
        '/static/images/icons/catalog_done.svg'         => '/static/images/icons/catalog-done.svg',
        '/static/images/icons/catalog_light.svg'        => '/static/images/icons/catalog-light.svg',
        '/static/images/icons/chain_1.svg'              => '/static/images/icons/chain.svg',
        '/static/images/icons/changeset_lc.svg'         => '/static/images/icons/changeset-lc.svg',
        '/static/images/icons/chart_bar.svg'            => '/static/images/icons/chart-bar.svg',
        '/static/images/icons/chart_curve.svg'          => '/static/images/icons/chart-curve.svg',
        '/static/images/icons/chart_line.svg'           => '/static/images/icons/chart-line.svg',
        '/static/images/icons/chart_pie.svg'            => '/static/images/icons/chart-pie.svg',
        '/static/images/icons/cog_edit.svg'             => '/static/images/icons/cog-edit.svg',
        '/static/images/icons/cog_go.svg'               => '/static/images/icons/cog-go.svg',
        '/static/images/icons/comment_blue.svg'         => '/static/images/icons/topic-comment.svg',
        '/static/images/icons/comment_new.svg'          => '/static/images/icons/comment-new.svg',
        '/static/images/icons/commit_1.svg'             => '/static/images/icons/commit.svg',
        '/static/images/icons/commite_new.svg'          => '/static/images/icons/commite-new.svg',
        '/static/images/icons/combo_box.svg'            => '/static/images/icons/combo-box.svg',
        '/static/images/icons/control_equalizer.svg'    => '/static/images/icons/control-equalizer.svg',
        '/static/images/icons/control_equalizer.svg'    => '/static/images/icons/control-equalizer.svg',
        '/static/images/icons/control_pause.svg'        => '/static/images/icons/control-pause.svg',
        '/static/images/icons/cut_edit.svg'             => '/static/images/icons/cut-edit.svg',
        '/static/images/icons/data_editor.svg'          => '/static/images/icons/data-editor.svg',
        '/static/images/icons/database_refresh.svg'     => '/static/images/icons/database-refresh.svg',
        '/static/images/icons/database_save.svg'        => '/static/images/icons/database-save.svg',
        '/static/images/icons/debug_view.svg'           => '/static/images/icons/debug-view.svg',
        '/static/images/icons/delete_all.svg'           => '/static/images/icons/delete-all.svg',
        '/static/images/icons/delete_red.svg'           => '/static/images/icons/delete-grid-row.svg',
        '/static/images/icons/door_out.svg'             => '/static/images/icons/door-out.svg',
        '/static/images/icons/downloads_favicon.svg'    => '/static/images/icons/downloads-favicon.svg',
        '/static/images/icons/drive_add.svg'            => '/static/images/icons/drive-add.svg',
        '/static/images/icons/drive_delete.svg'         => '/static/images/icons/drive-delete.svg',
        '/static/images/icons/drive_disk.svg'           => '/static/images/icons/drive-disk.svg',
        '/static/images/icons/drive_edit.svg'           => '/static/images/icons/drive-edit.svg',
        '/static/images/icons/drive_go.svg'             => '/static/images/icons/drive-go.svg',
        '/static/images/icons/element_new_after.svg'    => '/static/images/icons/element-new-after.svg',
        '/static/images/icons/element_new_before.svg'   => '/static/images/icons/element-new-before.svg',
        '/static/images/icons/element_new.svg'          => '/static/images/icons/element-new.svg',
        '/static/images/icons/element_next.svg'         => '/static/images/icons/element-next.svg',
        '/static/images/icons/element_previous.svg'     => '/static/images/icons/element-previous.svg',
        '/static/images/icons/log_e.svg'                => '/static/images/icons/error.svg',
        '/static/images/icons/extjs_example.svg'        => '/static/images/icons/extjs-example.svg',
        '/static/images/icons/extjs_examples.svg'       => '/static/images/icons/extjs-examples.svg',
        '/static/images/icons/folder_new.svg'           => '/static/images/icons/favorite-folder.svg',
        '/static/images/icons/file_extension_zip.svg'   => '/static/images/icons/file-extension/file-extension-zip.svg',
        '/static/images/icons/folder_add.svg'           => '/static/images/icons/folder-add.svg',
        '/static/images/icons/folder_database.svg'      => '/static/images/icons/folder-database.svg',
        '/static/images/icons/folder_delete_1.svg'      => '/static/images/icons/folder-delete.svg',
        '/static/images/icons/folder_delete.svg'        => '/static/images/icons/folder-delete.svg',
        '/static/images/icons/folder_edit.svg'          => '/static/images/icons/folder-edit.svg',
        '/static/images/icons/folder_explore.svg'       => '/static/images/icons/folder-explore.svg',
        '/static/images/icons/folder_find.svg'          => '/static/images/icons/folder-find.svg',
        '/static/images/icons/folder_go.svg'            => '/static/images/icons/folder-go.svg',
        '/static/images/icons/folder_heart.svg'         => '/static/images/icons/folder-heart.svg',
        '/static/images/icons/favorite_new.svg'         => '/static/images/icons/folder-new.svg',
        '/static/images/icons/form_custom.svg'          => '/static/images/icons/form-custom.svg',
        '/static/images/icons/go_color.svg'             => '/static/images/icons/go-color.svg',
        '/static/images/icons/group_go.svg'             => '/static/images/icons/group-go.svg',
        '/static/images/icons/icon_wand.svg'            => '/static/images/icons/icon-wand.svg',
        '/static/images/icons/item_rename.svg'          => '/static/images/icons/item-rename.svg',
        '/static/images/icons/jboss_icon.svg'           => '/static/images/icons/jboss-icon.svg',
        '/static/images/icons/key_add.svg'              => '/static/images/icons/key-add.svg',
        '/static/images/icons/key_delete.svg'           => '/static/images/icons/key-delete.svg',
        '/static/images/icons/keyboard_add.svg'         => '/static/images/icons/keyboard-add.svg',
        '/static/images/icons/layout_edit.svg'          => '/static/images/icons/layout-edit.svg',
        '/static/images/icons/leaf_1.svg'               => '/static/images/icons/leaf.svg',
        '/static/images/icons/life_cycle_general.svg'   => '/static/images/icons/life-cycle-general.svg',
        '/static/images/icons/life_cycle_rol.svg'       => '/static/images/icons/life-cycle-rol.svg',
        '/static/images/icons/life_cycle.svg'           => '/static/images/icons/life-cycle.svg',
        '/static/images/icons/lightbulb_1.svg'          => '/static/images/icons/lightbulb.svg',
        '/static/images/icons/lightbulb_off.svg'        => '/static/images/icons/lightbulb-off.svg',
        '/static/images/icons/log_d.svg'                => '/static/images/icons/log-debug.svg',
        '/static/images/icons/error_red.svg'            => '/static/images/icons/error.svg',
        '/static/images/icons/log_w_1.svg'              => '/static/images/icons/job-log-warn.svg',
        '/static/images/icons/mark_unread.svg'          => '/static/images/icons/mark-unread.svg',
        '/static/images/icons/mind_map-26.svg'          => '/static/images/icons/mind-map.svg',
        '/static/images/icons/package_add.svg'          => '/static/images/icons/package-add.svg',
        '/static/images/icons/page_copy.svg'            => '/static/images/icons/page-copy.svg',
        '/static/images/icons/page_edit.svg'            => '/static/images/icons/page-edit.svg',
        '/static/images/icons/page_new.svg'             => '/static/images/icons/page-new.svg',
        '/static/images/icons/page_refresh.svg'         => '/static/images/icons/page-refresh.svg',
        '/static/images/icons/page_up.svg'              => '/static/images/icons/page-up.svg',
        '/static/images/icons/pie_chart.svg'            => '/static/images/icons/pie-chart.svg',
        '/static/images/icons/priority_request.svg'     => '/static/images/icons/priority-request.svg',
        '/static/images/icons/project_small_child.svg'  => '/static/images/icons/project-small-child.svg',
        '/static/images/icons/referenced_in.svg'        => '/static/images/icons/referenced-in.svg',
        '/static/images/icons/references_out.svg'       => '/static/images/icons/references-out.svg',
        '/static/images/icons/register_view.svg'        => '/static/images/icons/register-view.svg',
        '/static/images/icons/release_explorer.svg'     => '/static/images/icons/release-explorer.svg',
        '/static/images/icons/release_lc.svg'           => '/static/images/icons/release-lc.svg',
        '/static/images/icons/rename_items.svg'         => '/static/images/icons/rename-items.svg',
        '/static/images/icons/report_default.svg'       => '/static/images/icons/repo.svg',
        '/static/images/icons/repo_default.svg'         => '/static/images/icons/report-default.svg',
        '/static/images/icons/report_dist.svg'          => '/static/images/icons/report-dist.svg',
        '/static/images/icons/report_magnify.svg'       => '/static/images/icons/report-magnify.svg',
        '/static/images/icons/restart_new.svg'          => '/static/images/icons/restart-new.svg',
        '/static/images/icons/revision_create.svg'      => '/static/images/icons/revision-create.svg',
        '/static/images/icons/revision_del.svg'         => '/static/images/icons/revision-del.svg',
        '/static/images/icons/revision_rename.svg'      => '/static/images/icons/revision-rename.svg',
        '/static/images/icons/script_edit.svg'          => '/static/images/icons/script-edit.svg',
        '/static/images/icons/server_restart.svg'       => '/static/images/icons/server-restart.svg',
        '/static/images/icons/share_this.svg'           => '/static/images/icons/share-this.svg',
        '/static/images/icons/slot_green.svg'           => '/static/images/icons/create-slot-active.svg',
        '/static/images/icons/slot_red.svg'             => '/static/images/icons/create-slot-inactive.svg',
        '/static/images/icons/star_off.svg'             => '/static/images/icons/star-off.svg',
        '/static/images/icons/step_post.svg'            => '/static/images/icons/step-post.svg',
        '/static/images/icons/step_pre.svg'             => '/static/images/icons/step-pre.svg',
        '/static/images/icons/table_edit.svg'           => '/static/images/icons/table-edit.svg',
        '/static/images/icons/table_lightning.svg'      => '/static/images/icons/table-lightning.svg',
        '/static/images/icons/tag_blocked.svg'          => '/static/images/icons/tag-blocked.svg',
        '/static/images/icons/tag_edit.svg'             => '/static/images/icons/tag-edit.svg',
        '/static/images/icons/tag_merged.svg'           => '/static/images/icons/tag-merged.svg',
        '/static/images/icons/tag_pending.svg'          => '/static/images/icons/tag-pending.svg',
        '/static/images/icons/topic_in.svg'             => '/static/images/icons/topic-in.svg',
        '/static/images/icons/topic_lc.svg'             => '/static/images/icons/topic-lc.svg',
        '/static/images/icons/topic_out_open.svg'       => '/static/images/icons/topic-out-open.svg',
        '/static/images/icons/topic_out.svg'            => '/static/images/icons/topic-out.svg',
        '/static/images/icons/traffic_lights_green.svg' => '/static/images/icons/traffic-lights-green.svg',
        '/static/images/icons/traffic_lights_red.svg'   => '/static/images/icons/traffic-lights-red.svg',
        '/static/images/icons/traffic_lights_yellow.svg' => '/static/images/icons/traffic-lights-yellow.svg',
        '/static/images/icons/traffic_lights.svg'        => '/static/images/icons/traffic-lights.svg',
        '/static/images/icons/user_add.svg'              => '/static/images/icons/user-add.svg',
        '/static/images/icons/user_delete.svg'           => '/static/images/icons/user-delete.svg',
        '/static/images/icons/user_female.svg'           => '/static/images/icons/user-female.svg',
        '/static/images/icons/user_suit.svg'             => '/static/images/icons/user-suit.svg',
        '/static/images/icons/window_min.svg'            => '/static/images/icons/window-min.svg',
        '/static/images/icons/wipe_cache.svg'            => '/static/images/icons/wipe-cache.svg',
        '/static/images/icons/folder_magnify.png'        => '/static/images/icons/folder-explore.svg',
        '/static/images/silk/chart_curve.png'            => '/static/images/icons/chart-curve.svg',
        '/static/images/silk/world.png'                  => '/static/images/icons/world.svg',
        '/static/images/icons/changesets.png'            => '/static/images/icons/changesets.svg',
        '/static/images/icons/class.gif'                 => '/static/images/icons/class.svg',
        '/static/images/icons/roadmap.png'               => '/static/images/icons/dashlet-topic-roadmap.svg',
        '/static/images/nature/nature.png'               => '/static/images/icons/nature.svg',
        '/static/images/icons/rename_items.png'          => '/static/images/icons/rename-items.svg',
        '/static/images/icons/page_lens.png'             => '/static/images/icons/page-magnify.svg',
        '/static/images/icons/admin_request.png'         => '/static/images/icons/fieldlet-checkbox.svg',
        '/amazon/amazon_ws_16.png'                       => '/amazon/logo-amazon.svg',
        '/static/images/circular/cog.png'                => '/static/images/icons/cog.svg',
        '/static/images/icons/folder-database.svg'       => '/static/images/icons/ci-report-category.svg',
        '/static/images/icons/folder-explore.svg'        => '/static/images/icons/ci-report-field.svg',
        '/static/images/icons/folder-find.svg'           => '/static/images/icons/ci-report-filter.svg',
        '/static/images/icons/folder-go.svg'             => '/static/images/icons/ci-report-sort.svg',
        '/static/images/icons/field.svg'                 => '/static/images/icons/ci-report-selected-field.svg',
        '/eclipse/eclipse.gif'                           => '/javatools/logo-eclipse.svg',
    );

    my $found_icon = '';

    if ($icon) {
        $found_icon = $old_new_icon{$icon};
    }

    return $found_icon;
}

sub downgrade {
}

1;
