CREATE TABLE bali_sem
(	SEM VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(4000 BYTE), 
	BL VARCHAR2(1024 BYTE) DEFAULT '*' NOT NULL ENABLE, 
	ACTIVE NUMBER DEFAULT 1 NOT NULL ENABLE, 
	SLOTS NUMBER DEFAULT 1, 
	QUEUE_MODE VARCHAR2(255 BYTE) DEFAULT 'queued', 
    CONSTRAINT bali_sem_pk PRIMARY KEY ( sem, bl )
);

CREATE TABLE BALI_SEM_QUEUE 
(	ID NUMBER, 
	WHO VARCHAR2(1024 BYTE), 
	HOST VARCHAR2(20 BYTE) DEFAULT 'localhost', 
	PID NUMBER, 
	STATUS VARCHAR2(255 BYTE) DEFAULT 'idle' NOT NULL ENABLE, 
	ACTIVE NUMBER DEFAULT 1 NOT NULL ENABLE, 
	SEQ NUMBER DEFAULT 0, 
	RUN_NOW NUMBER DEFAULT 0 NOT NULL ENABLE, 
	TS_REQUEST DATE DEFAULT SYSDATE, 
	TS_GRANT DATE, 
	TS_RELEASE VARCHAR2(20 BYTE), 
	SEM VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	EXPIRE_ON DATE, 
	BL VARCHAR2(255 BYTE) DEFAULT '*', 
	CALLER VARCHAR2(4000 BYTE), 
	ID_JOB NUMBER, 
	WHO_ID VARCHAR2(1024 BYTE), 
	WAIT_SECS NUMBER, 
	BUSY_SECS VARCHAR2(20 BYTE)
);

CREATE SEQUENCE BALI_SEM_QUEUE_SEQ MINVALUE 1
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE OR REPLACE TRIGGER BALI_SEM_QUEUE_TRG 
        BEFORE INSERT ON BALI_SEM_QUEUE
        REFERENCING NEW AS NEW OLD AS OLD
        FOR EACH ROW
        BEGIN
           SELECT BALI_SEM_QUEUE_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
        END;
/

ALTER TRIGGER BALI_SEM_QUEUE_TRG ENABLE;
 

