(function(params){
    var data = params.data || {};
    return [
        //{ xtype:'textfield', fieldLabel: _('User'), name: 'user', value: params.data.user },
        { xtype:'textarea', fieldLabel: _('Path'), height: 80, name: 'path', value: params.data.path },
        new Baseliner.ArrayGrid({ 
            fieldLabel:_('Arguments'), 
            name: 'args', 
            value: params.data.args,
            description:_('Command arguments'), 
            default_value:'.' 
        }), 
        new Baseliner.ArrayGrid({ 
            fieldLabel:_('Output Files'), 
            name: 'output_files', 
            height: 120,
            value: params.data.output_files,
            description:_('Output or log files generated by this command'), 
            default_value: params.data.home || '${job_dir}/${project}/file.log' 
        }), 
        { xtype:'textarea', fieldLabel: _('Home Directory'), height: 80, name: 'home', value: params.data.home },
        { xtype:'textarea', fieldLabel: _('Stdin'), height: 80, name: 'stdin', value: params.data.stdin },
        new Baseliner.ErrorOutputTabs({ data: data }) 
    ]
})



