(function(params){
    var data = params.data || {};
    
    // error handling
    var errors = new Baseliner.ComboSingle({ fieldLabel: _('Errors'), name:'errors', value: data.errors || 'fail', data: [
        'fail',
        'warn',
        'custom',
        'silent'
    ]});
    var custom_error = new Ext.Panel({ 
        layout:'column', fieldLabel:_('Return Codes'), frame: true, 
        hidden: data.errors!='custom',
        items: [
            { layout:'form', columnWidth:.33, labelAlign:'top', frame: true, items: { xtype:'textfield', anchor:'100%', fieldLabel: _('Ok'), name: 'rc_ok', value: data.rc_ok } },
            { layout:'form', columnWidth:.33, labelAlign:'top', frame: true, items: { xtype:'textfield', anchor:'100%', fieldLabel: _('Warn'), name: 'rc_warn', value: data.rc_warn } },
            { layout:'form', columnWidth:.33, labelAlign:'top', frame: true, items: { xtype:'textfield', anchor:'100%', fieldLabel: _('Error'), name: 'rc_error', value: data.rc_error } }
        ],
        show_hide : function(){ 
            errors.getValue()=='custom' ? this.show() : this.hide();
            this.doLayout();
        }
    });
    errors.on('select', function(){ custom_error.show_hide() });

    return [
        //{ xtype:'textfield', fieldLabel: _('User'), name: 'user', value: params.data.user },
        { xtype:'textarea', fieldLabel: _('Path'), height: 80, name: 'path', value: params.data.path },
        { xtype:'tabpanel', height: 430, fieldLabel:_('Options'), activeTab:0, items:[
            new Baseliner.ArrayGrid({ 
                title:_('Arguments'), 
                name: 'args', 
                value: params.data.args,
                description:_('Command arguments'), 
                default_value:'.' 
            }), 
            new Baseliner.DataEditor({ 
                   name:'environment', title: _('Environment'), 
                   hide_save: true, hide_cancel: true,
                   data: data.environment || {} }),
            new Baseliner.ArrayGrid({ 
                title:_('Output Files'), 
                name: 'output_files', 
                height: 120,
                value: params.data.output_files,
                description:_('Output or log files generated by this command'), 
                default_value: params.data.home || '${job_dir}/${project}/file.log' 
            }) 
            ]
        }, 
        { xtype:'textarea', fieldLabel: _('Home Directory'), height: 80, name: 'home', value: params.data.home },
        { xtype:'textarea', fieldLabel: _('Stdin'), height: 80, name: 'stdin', value: params.data.stdin },
        errors,
        custom_error,
        new Baseliner.ErrorOutputTabs({ data: data }) 
    ]
})



