lang: en_US.UTF-8
port: 3000
license:
  end_date: 2014-12-31
  id: trial_customer
  lic_data: jOQ13CTUZqxDpqGuTCYbrAOBuwGoJBn4bNsCsJdnWCHNn+aAk4tIJBhSc1XB5K8UtBQE9qwB0LZjAAKTXKUBJo8ePA1aB31BYLKa6BZRPuECDRpqEDghAL2BCET+PA4URynB
  lic_key: dyJVUabhxlKvrWZVxjL2FrALip6u4dc2tTSSsN3sFg7IGSVGcIrj/FBOcJ0GAIGguXiTvYlAc1xGYNiNLagQUTlLWSo7Ww2KmUzNFaCtnpgotf8/B2IKMWI/sC0NIGg3JLSyrP+wyQMI258xdWnoKiPP8owWQHEDVkw5LFW1yL0=
  name: Trial Customer
  private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIICXAIBAAKBgQDdf3HLmPfRF+QrnWFPOV89kCHzPCY71ha4AG6Zx2U3kT1jtMu5

    vuNWfYkV2DhNsvWojKGhVGudFKld1J7o+XMa1fxZlapk7awHKI/DcKvPheKfk9sA

    jz63pQ6fNqB1NQxdHBAUp9e0FFSUXhvPcrWiPkHLOnRivlcrLQZ2kdUwvwIDAQAB

    AoGAeWgrpZ845oEj7cwb1GLsE0B3e21Sv6V/WmfSN7QVhLm1Xntw12UMExJIG5Mi

    eWRIRpSe22D8g2MZ2nZ6i9R/BAdwYEFlCo0NngcPqmRfyu8RRw/TIxU7akAq4256

    kP+Un6Rrs72FNJ2bAqYRUuhZ84QTVfNgVAbcnur8Z5ixkRECQQD1ceu0PWDW1xpu

    QQR+mzAu1ylPR/nQC7Lcaj5GS6Lc+NKK9HF/4vcEWVbgA0hiy97r4m1QjcChil5W

    Q1VSHopFAkEA5wXkTAeiT+2wXGyyD3tluQwwHthN4ajlQkUdIIVmY9Z8jHAHYAyr

    I/eIV5ku86hJAF5MNMyKQjIORxiEHWXhMwJAI5gBtoGwKXfIPXTwUevvcNuDAhxN

    /f20UoKVxVvyoljzL3ODgihH6jmKf7H6LVmjWlHbyHLGHKcURy48kUwcgQJAT8P1

    A1tPa5GB5yeQg0/z22Sd6Mh+e3+5SJxcZjIpHCeecU7s/PjizlRVOwmk8HQWYI4u

    ebx1sE1gKKQKWawniQJBAKwnz5i8lXe9W7jl5D0fYQQ4xnINdfVKhPrq/GKUGh3u

    Y2OZooedzh9GM0Wst9CGrOXithn0Ts5O8US0TjbcT5s=

    -----END RSA PRIVATE KEY-----

'
  users: 5
